### ISSUE TITLE
How to Use hole Image to stop runner when it come at hole position?

### ISSUE THREAD

**Issue by kamabhavik** [UnicornTV/Swift-Example-Introduction-to-SpriteKit#1]
Hi Clayton McIlrath i have gone through this demo.. and this is really owesome for beginner..i want to learn more this in demo..i have downloaded the source from GITHUB now i want to use the image named "hole" in ground.. and i want that while running whenever the hole is come that boy running is disapper..please let me know how can i do it..thanks & Regards

**Comment by thinkclay** [comment]
I will post a new tutorial in the near future. Make sure to subscribe to newsletters on the website and you will see it when posted.
